[package]
name = "netlink-packet-generic"
version = "0.1.0"
authors = ["Leo <leo881003@gmail.com>"]
edition = "2018"

homepage = "https://github.com/little-dude/netlink"
keywords = ["netlink", "linux"]
license = "MIT"
readme = "../README.md"
repository = "https://github.com/little-dude/netlink"
description = "netlink packet types"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.86"
byteorder = "1.4.2"
netlink-packet-core = { path = "../netlink-packet-core", version = "0.2" }
netlink-packet-utils = { path = "../netlink-packet-utils", version = "0.4" }
